apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: elasticsearch-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Elasticsearch is the Schema for the elasticsearches API
      displayName: Elasticsearch
      kind: Elasticsearch
      name: elasticsearches.logging.example.com
      version: v1alpha1
  description: simple elasticsearch operator
  displayName: elasticsearch
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - elasticsearch
  links:
  - name: Elasticsearch Operator
    url: https://elasticsearch-operator.domain
  maturity: alpha
  provider:
    name: myorganisation
  version: 0.0.0
